#ifndef KINGDOM_DEFS_H_INCLUDED
#define KINGDOM_DEFS_H_INCLUDED


typedef enum {
    KD_APPSTATE_STOPPED,
    KD_APPSTATE_RUNNING,
    KD_APPSTATE_PAUSED,
    KD_APPSTATE_BACKGROUND
} KD_APPSTATE;

#endif // KINGDOM_DEFS_H_INCLUDED
