#ifndef BASALTIC_DEFS_H_INCLUDED
#define BASALTIC_DEFS_H_INCLUDED

#include "htw_core.h"

typedef struct bc_ModelData bc_ModelData;

typedef enum {
    BC_SUPERVISOR_SIGNAL_NONE,
    BC_SUPERVISOR_SIGNAL_START_MODEL,
    BC_SUPERVISOR_SIGNAL_STOP_MODEL,
    BC_SUPERVISOR_SIGNAL_RESTART_MODEL,
    BC_SUPERVISOR_SIGNAL_STOP_PROCESS,
} bc_SupervisorSignal;

typedef enum {
    BC_PROCESS_STATE_STOPPED,
    BC_PROCESS_STATE_RUNNING,
    BC_PROCESS_STATE_PAUSED,
    BC_PROCESS_STATE_BACKGROUND
} bc_ProcessState;

typedef enum bc_StartupMode {
    BC_STARTUP_MODE_NO_MODEL,
    BC_STARTUP_MODE_START_MODEL,
    BC_STARTUP_MODE_LOAD_MODEL
} bc_StartupMode;

// TODO: move to view module
typedef enum bc_InterfaceMode {
    BC_INTERFACE_MODE_SYSTEM_MENU,
    BC_INTERFACE_MODE_GAMEPLAY,
    BC_INTERFACE_MODE_EDITOR
} bc_InterfaceMode;

#endif // BASALTIC_DEFS_H_INCLUDED
